version: '3.9'

services:
  assistant-db:
    image: ankane/pgvector
    container_name: assistant-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  assistant-ui:
    image: aronweiler/assistant:latest
    container_name: assistant-ui
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=host.docker.internal
    ports:
      - 8500:8500
    volumes:
      - ./tmp/assistant-ui-config/:/config/

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    restart: always     
    env_file:
      - .env 
    ports:
      - '5672:5672'
      - '15672:15672'

  discord-bot:
    image: aronweiler/assistant:latest
    container_name: discord-bot
    restart: always
    entrypoint: >
      sh -c 'if [ "$ENABLE_DISCORD_BOT" = "true" ]; then python src/discord/bot.py; else sleep infinity; fi'
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=host.docker.internal
