version: '3.9'

services:
  assistant-db:
    image: ankane/pgvector
    container_name: assistant-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  assistant-ui:
    image: aronweiler/assistant:latest
    container_name: assistant-ui
    restart: always
    env_file:
      - .env
    ports:
      - 8500:8500

  discord-bot:
    image: aronweiler/assistant:latest
    container_name: discord-bot
    restart: always
    entrypoint: python src/discord/bot.py
    env_file:
      - .env