version: "3.9"

services:
  jarvis-database:
    build: 
      context: .
      dockerfile: src/database/Dockerfile
    container_name: jarvis-database
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
    ports:
      - 5433:5432

  jarvis-ui:
    build: 
      context: .
      dockerfile: src/ui/Dockerfile
    container_name: jarvis-ui
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - API_USER_HOST=jarvis-api-user
      - API_USER_PORT=8101
      - API_DOCUMENT_HOST=jarvis-api-document
      - API_DOCUMENT_PORT=8102      
      - API_CODE_HOST=jarvis-api-code
      - API_CODE_PORT=8103
      - API_CONVERSATION_HOST=jarvis-api-conversation
      - API_CONVERSATION_PORT=8104
      - RABBITMQ_HOST=jarvis-rabbitmq
    ports:
      - 8600:8600
    volumes:
      - shared_data:/app/shared

  jarvis-ui-react:
    build: ./src/react-ui
    container_name: jarvis-ui-react
    ports:
      - "3000:3000"
    volumes:
      - ./src/react-ui/app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_USER_HOST=jarvis-api-user
      - REACT_APP_API_USER_PORT=8101

  jarvis-api-user:
    build: 
      context: .
      dockerfile: ./src/api/user/Dockerfile
    container_name: jarvis-api-user
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - RABBITMQ_HOST=jarvis-rabbitmq
    ports:
      - 8101:8101

  jarvis-api-document:
    build: 
      context: .
      dockerfile: ./src/api/document/Dockerfile
    container_name: jarvis-api-document
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - RABBITMQ_HOST=jarvis-rabbitmq
    ports:
      - 8102:8102
    volumes:
      - shared_data:/app/shared

  jarvis-api-code:
    build: ./src/api/code
    container_name: jarvis-api-code
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - RABBITMQ_HOST=jarvis-rabbitmq
    ports:
      - 8103:8103

  jarvis-api-conversation:
    build: ./src/api/conversation
    container_name: jarvis-api-conversation
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - RABBITMQ_HOST=jarvis-rabbitmq
    ports:
      - 8104:8104

  jarvis-worker-document-processing:
    build: 
      context: .
      dockerfile: ./src/workers/document_processing/Dockerfile
    container_name: jarvis-worker-document-processing
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=jarvis-database
      - RABBITMQ_HOST=jarvis-rabbitmq
    volumes:
      - shared_data:/app/shared

  jarvis-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: jarvis-rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  shared_data: