apiVersion: v1
kind: Service
metadata:
  name: jarvis-zipbot
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jarvis.zipbot.ai
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8600
  selector:
    io.kompose.service: jarvis-ui