apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jarvis-db-data
  name: jarvis-db-data
  namespace: jarvis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
