on: [workflow_dispatch]
# on:
#   pull_request:
#     branches: [ main ]

jobs:
  code_review:
    runs-on: ubuntu-latest
    name: Code review job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

    # Example 1
      - name: Get all test, doc and src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            python:
            - '**/*.py'            
        # Optionally set `files_yaml_from_source_file` to read the YAML from a file. e.g `files_yaml_from_source_file: .github/changed-files.yml`
                

        # Run the code review
      - name: Start code review step
        id: code_review
        uses: aronweiler/codereviewer@main
        env:
          CHANGES: ${{ steps.changed-files.outputs.all_changed_files }}

      # Use the output from the code_review step
      - name: Get the summary
        run: echo "Summary- ${{ steps.code_review.outputs.summary }}"
