# Name the workflow
name: Code Review

on: [workflow_dispatch]
# on:
#   pull_request:
#     branches: [ main ]

jobs:
  code_review:
    runs-on: ubuntu-latest
    name: Code review job
    permissions:
      pull-requests: read

    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.        
    
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37        
        with:
          separator: ","          

      - name: List all changed files
        run: |
            for file in ${{ steps.changed-files.outputs.unmerged_files }}; do
                echo "$file is not merged"
            done
    
        # Run the code review
      - name: Start code review step
        id: code_review
        uses: aronweiler/codereviewer@main
        env:
          CHANGES: ${{ steps.changed-files.outputs.unmerged_files }}

      # Use the output from the code_review step
      - name: Get the summary
        run: echo "Summary- ${{ steps.code_review.outputs.summary }}"